remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Coding On Jupiter
email: xufei1990@gmail.com
paginate: 25
paginate_path: "/page:num/"

comments: false  # enable comments
disqus:          # disqus account

mathjax: true # Mathematics
mermaid: true # Diagrams
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-seo-tag

language: zh-cn
url: "https://xufeisofly.github.io"



